CREATE TABLE IF NOT EXISTS especialidade (
    id int GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(100) NOT NULL,
    CONSTRAINT pk_especialidade PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS endereco (
    id int GENERATED BY DEFAULT AS IDENTITY,
    rua varchar(150),
    bairro varchar(100),
    cidade varchar(100),
    estado varchar(50),
    CONSTRAINT pk_endereco PRIMARY KEY (id)
);

CREATE TABLE  IF NOT EXISTS convenio (
    id int GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(100) NOT NULL,
    valor numeric(10,2),
    CONSTRAINT pk_convenio PRIMARY KEY (id),
    CONSTRAINT ck_convenio_valor CHECK (valor >= 0)
);

CREATE TABLE IF NOT EXISTS medico (
    id int GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(150) NOT NULL,
    cpf varchar(11) NOT NULL,
    endereco_id int UNIQUE,
    CONSTRAINT pk_medico PRIMARY KEY (id),
    CONSTRAINT uq_medico_cpf UNIQUE (cpf),
    CONSTRAINT fk_medico_endereco FOREIGN KEY (endereco_id) REFERENCES endereco(id)
);

CREATE TABLE IF NOT EXISTS paciente (
    id int GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(150) NOT NULL,
    cpf varchar(11) NOT NULL,
    data_nascimento date,
    telefone varchar(20),
    email varchar(100),
    convenio_id int,
    endereco_id int UNIQUE,
    CONSTRAINT pk_paciente PRIMARY KEY (id),
    CONSTRAINT uq_paciente_cpf UNIQUE (cpf),
    CONSTRAINT fk_paciente_convenio FOREIGN KEY (convenio_id) REFERENCES convenio(id),
    CONSTRAINT fk_paciente_endereco FOREIGN KEY (endereco_id) REFERENCES endereco(id)
);


CREATE TABLE IF NOT EXISTS consulta (
    id int GENERATED BY DEFAULT AS IDENTITY,
    valor numeric(10,2) CHECK (valor >= 0),
    data_hora_inicio timestamp NOT NULL,
    data_hora_fim timestamp,
    realizado boolean DEFAULT FALSE,
    medico_id int NOT NULL,
    paciente_id int NOT NULL,
    CONSTRAINT pk_consulta PRIMARY KEY (id),
    CONSTRAINT fk_consulta_medico FOREIGN KEY (medico_id) REFERENCES medico(id),
    CONSTRAINT fk_consulta_paciente FOREIGN KEY (paciente_id) REFERENCES paciente(id)
);

CREATE TABLE IF NOT EXISTS pagamento_consulta (
    id int GENERATED BY DEFAULT AS IDENTITY,
    valor numeric(10,2) NOT NULL CHECK (valor >= 0),
    data_hora timestamp,
    realizado boolean DEFAULT FALSE,
    consulta_id int UNIQUE,
    CONSTRAINT pk_pagamento PRIMARY KEY (id),
    CONSTRAINT fk_pagamento_consulta FOREIGN KEY (consulta_id) REFERENCES consulta(id)
);

CREATE TABLE IF NOT EXISTS medico_especialidade (
    medico_id int NOT NULL,
    especialidade_id int NOT NULL,
    CONSTRAINT pk_medico_especialidade PRIMARY KEY (medico_id, especialidade_id),
    CONSTRAINT fk_mes_medico FOREIGN KEY (medico_id) REFERENCES medico(id),
    CONSTRAINT fk_mes_especialidade FOREIGN KEY (especialidade_id) REFERENCES especialidade(id)
);

ALTER TABLE pagamento_consulta
ADD COLUMN paciente_id int,
ADD CONSTRAINT fk_pagamento_paciente FOREIGN KEY (paciente_id)
REFERENCES paciente(id);

ALTER TABLE medico
ALTER COLUMN endereco_id SET NOT NULL;

ALTER TABLE paciente
ALTER COLUMN endereco_id SET NOT NULL;

