-- Endereco
INSERT INTO Endereco (id, rua, bairro, cidade, estado) VALUES
                                                           (1, 'Av. Brasil, 1234', 'Centro', 'São Paulo', 'SP'),
                                                           (2, 'Rua das Flores, 500', 'Jardins', 'Rio de Janeiro', 'RJ'),
                                                           (3, 'Alameda dos Anjos, 101', 'Boa Viagem', 'Recife', 'PE'),
                                                           (4, 'Estrada do Sol, 99', 'Lago Sul', 'Brasília', 'DF'),
                                                           (5, 'Travessa da Lua, 20', 'Savassi', 'Belo Horizonte', 'MG'),
                                                           (6, 'Rua Sete de Setembro, 321', 'Moinhos de Vento', 'Porto Alegre', 'RS'),
                                                           (7, 'Avenida Atlântica, 777', 'Meireles', 'Fortaleza', 'CE'),
                                                           (8, 'Rua da Paz, 15', 'Caminho das Árvores', 'Salvador', 'BA'),
                                                           (9, 'Rua XV de Novembro, 456', 'Centro Cívico', 'Curitiba', 'PR'),
                                                           (10, 'Rua Getúlio Vargas, 888', 'Setor Oeste', 'Goiânia', 'GO'),
                                                           (11, 'Avenida Paulista, 100', 'Bela Vista', 'São Paulo', 'SP'),
                                                           (12, 'Rua Barão de Itamaracá, 55', 'Tijuca', 'Rio de Janeiro', 'RJ'),
                                                           (13, 'Rua das Acácias, 10', 'Campinas', 'Goiânia', 'GO'),
                                                           (14, 'Alameda Santos, 2000', 'Cerqueira César', 'São Paulo', 'SP'),
                                                           (15, 'Rua Voluntários da Pátria, 33', 'Botafogo', 'Rio de Janeiro', 'RJ'),
                                                           (16, 'Rua das Acácias, 100', 'Nova Iguaçu', 'Duque de Caxias', 'RJ'),
                                                           (17, 'Av. Litorânea, 300', 'Ponta Negra', 'Natal', 'RN'),
                                                           (18, 'Rua Gávea, 50', 'Jardim Paulista', 'São Paulo', 'SP'),
                                                           (19, 'Travessa da Misericórdia, 45', 'Pelourinho', 'Salvador', 'BA'),
                                                           (20, 'Estrada Real, 171', 'Funcionários', 'Belo Horizonte', 'MG'),
                                                           (21, 'Av. Beira Mar, 222', 'Centro', 'Florianópolis', 'SC'),
                                                           (22, 'Rua Tamoios, 789', 'Vila Velha', 'Campinas', 'SP'),
                                                           (23, 'Praça da Sé, 1', 'Sé', 'São Paulo', 'SP'),
                                                           (24, 'Rua do Ouvidor, 88', 'Centro Histórico', 'Rio de Janeiro', 'RJ'),
                                                           (25, 'Rua dos Imigrantes, 404', 'Setor Sul', 'Goiânia', 'GO'),
                                                           (26, 'Av. Afonso Pena, 1000', 'Cruzeiro', 'Belo Horizonte', 'MG'),
                                                           (27, 'Rua Quinze, 12', 'Aldeota', 'Fortaleza', 'CE'),
                                                           (28, 'Rua da Aurora, 60', 'Santo Antônio', 'Recife', 'PE'),
                                                           (29, 'Rua do Porto, 25', 'Centro', 'Santos', 'SP'),
                                                           (30, 'Av. Principal, 50', 'Lagoa', 'Porto Alegre', 'RS');
